require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 6.0
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - config/routes.rb

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/*'
    - 'config/routes.rb'
    - 'db/seeds.rb'

Rails:
  Enabled: true

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/application_helper.rb'

Rails/Present:
  Exclude:
    - 'config/puma.rb'

Rails/SkipsModelValidations:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

Style/Documentation:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
