version: '3.3'

services:
  postgres:
    image: "postgres"
    env_file:
      - '.env'
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
    driver: local
